version: "2"
services:
  lirc:
    container_name: lirc
    image: "${MAINTAINER}/${PLATFORM}-lirc"
    restart: always
    command: /usr/sbin/lircd --nodaemon --driver=default --device=/dev/lirc0
    privileged: true
    network_mode: host
    volumes:
    - /lib/modules:/lib/modules
    - ./lirc:/etc/lirc
    - /var/run/lirc:/var/run/lirc
    devices:
    - /dev/mem:/dev/mem