version: "2"
services:
  node-red:
    container_name: node-red.node-red
    image: "${MAINTAINER}/${PLATFORM}-node-red"
    restart: always
    privileged: true
    network_mode: host
    ports:
    - "1880:1880"
    volumes:
    - ../../config/node-red/node-red:/root/.node-red
    depends_on:
    - mosquitto
    - bluetooth-mqtt-proxy
  mosquitto:
    container_name: node-red.mosquitto
    image: "${MAINTAINER}/${PLATFORM}-mosquitto"
    restart: always
    network_mode: host
    ports:
    - "1883:1883"
    - "9001:9001"
    volumes:
    - ../../config/node-red/mosquitto/config:/mqtt/config
    - ../../config/node-red/mosquitto/data:/mqtt/data
  bluetooth-mqtt-proxy:
    container_name: node-red.bluetooth-mqtt-proxy
    image: "${MAINTAINER}/${PLATFORM}-bluetooth-mqtt-proxy"
    restart: always
    environment:
      DEBUG: "bluetooth-mqtt-proxy*"
    privileged: true
    network_mode: host
    volumes:
    - /var/run/dbus:/var/run/dbus
    - ../../config/node-red/bluetooth-mqtt-proxy:/root/.bluetooth-mqtt-proxy
