version: "2"
services:
  misfit-bolt-http:
    container_name: misfit-bolt-http
    image: "${MAINTAINER}/${PLATFORM}-misfit-bolt-http"
    restart: always
    command: misfit-bolt-http -p 3010
    # environment:
    #   DEBUG: "*misfit*"
    privileged: true
    network_mode: host
    ports:
    - "3010:3010"
    volumes:
    - /var/run/dbus:/var/run/dbus
  homebridge:
    container_name: homebridge
    image: "${MAINTAINER}/${PLATFORM}-homebridge"
    restart: always
    command: homebridge
    # environment:
    #   DEBUG: "*"
    privileged: true
    network_mode: host
    ports:
    - "51826:51826"
    volumes:
    - /var/run/dbus:/var/run/dbus
    - ./config:/root/.homebridge
    depends_on:
      - misfit-bolt-http
