version: "2"
services:
  lirc:
    container_name: nginx.nginx
    image: "${MAINTAINER}/${PLATFORM}-nginx"
    restart: always
    command: /usr/sbin/lircd --nodaemon --driver=default --device=/dev/lirc0 --listen=0.0.0.0:8765
    privileged: true
    network_mode: host
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=America/Los_Angeles
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ../../config/nginx/nginx:/config