version: "2"
services:
  lirc:
    container_name: lirc
    image: "${MAINTAINER}/${PLATFORM}-lirc"
    restart: always
    command: /usr/sbin/lircd --nodaemon --driver=default --device=/dev/lirc0
    privileged: true
    network_mode: host
    volumes:
    - /lib/modules:/lib/modules
    - ./lirc:/etc/lirc
    - /var/run/lirc:/var/run/lirc
    devices:
    - /dev/mem:/dev/mem
  lirc-state-api:
    container_name: lirc-state-api
    image: "${MAINTAINER}/${PLATFORM}-lirc-state-api"
    restart: always
    command: lirc-state-api -c=/root/config.json -p=3001
    ports:
    - "3001:3001"
    volumes:
    - ./lirc-state-api:/root
    - /var/run/lirc:/var/run/lirc
    depends_on:
      - lirc
  lirc-web:
    container_name: lirc-web
    image: "${MAINTAINER}/${PLATFORM}-lirc-web"
    restart: always
    command: lirc_web
    ports:
    - "3000:3000"
    volumes:
    - ./lirc-web:/root
    - /var/run/lirc:/var/run/lirc
    depends_on:
      - lirc
