version: "2"
services:
  homebridge:
    container_name: homekit-wink.homebridge
    image: "${MAINTAINER}/${PLATFORM}-homebridge-wink"
    restart: always
    privileged: true
    network_mode: host
    ports:
    - "51829:51829"
    volumes:
    - /var/run/dbus:/var/run/dbus
    - ./homebridge:/root/.homebridge
