version: "2"
services:
  portainer:
    container_name: admin.portainer
    image: "${MAINTAINER}/${PLATFORM}-portainer"
    restart: always
    ports:
    - "9000:9000"
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
  watchtower:
    container_name: admin.watchtower
    image: "${MAINTAINER}/${PLATFORM}-watchtower"
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  cloud9:
    container_name: admin.cloud9
    image: "${MAINTAINER}/${PLATFORM}-cloud9"
    restart: always
    command: node /c9sdk/server.js -w /data
    ports:
    - "8181:8181"
    volumes:
    - ../../:/data