version: "2"
services:
  openvpn-client:
    container_name: vpn-router.openvpn-client
    image: "${MAINTAINER}/${PLATFORM}-openvpn-client"
    restart: always
    command: openvpn --config /var/openvpn/openvpn.ovpn --auth-nocache --mute-replay-warnings
    privileged: true
    network_mode: host
    volumes:
    - ./openvpn-client:/var/openvpn
  prepare-dhcp:
    container_name: vpn-router.prepare-dhcp
    image: "${MAINTAINER}/${PLATFORM}-networking"
    command: /prepare-dhcp/run.sh
    privileged: true
    network_mode: host
    volumes:
    - /etc/sysctl.conf:/etc/sysctl.conf
    - ./prepare-dhcp:/prepare-dhcp
    - ./isc-dhcp-server:/isc-dhcp-server
    depends_on:
    - openvpn-client
  dhcp:
    container_name: vpn-router.isc-dhcp-server
    image: "${MAINTAINER}/${PLATFORM}-isc-dhcp-server"
    restart: always
    command: eth0
    network_mode: host
    volumes:
    - ./isc-dhcp-server/dhcpd.conf:/etc/dhcp/dhcpd.conf
    - ./isc-dhcp-server:/var/lib/dhcp
    depends_on:
    - prepare-dhcp
