version: "2"
services:
  lirc-web:
    container_name: lirc-web
    image: "${MAINTAINER}/${PLATFORM}-lirc-web"
    restart: always
    command: lirc_web
    ports:
    - "3000:3000"
    volumes:
    - ./lirc-web:/root
    - /var/run/lirc:/var/run/lirc
