version: "2"
services:
  portainer:
    container_name: portainer.portainer
    image: "${MAINTAINER}/${PLATFORM}-portainer"
    restart: always
    ports:
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ../../config/portainer/data:/data
 
