version: "2"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer:arm
    restart: always
    ports:
    - "80:9000"
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
