version: "2"
services:
  home-assistant:
    container_name: home-assistant
    image: "homeassistant/raspberrypi2-homeassistant"
    restart: always
    privileged: true
    ports:
    - "8123:8123"
    volumes:
    - ./home-assistant:/config
    devices:
    - /dev/ttyACM0:/dev/ttyACM0
