version: "2"
services:
  homebridge:
    container_name: homekit-nest.homebridge
    image: "${MAINTAINER}/${PLATFORM}-homebridge-nest"
    privileged: true
    network_mode: host
    ports:
    - "50040:50040"
    volumes:
    - /var/run/dbus:/var/run/dbus
    - ../../config/homekit-nest/homebridge:/root/.homebridge
