version: "2"
services:
  gogs:
    container_name: git.gogs
    hostname: git.local
    image: "${MAINTAINER}/${PLATFORM}-gogs"
    restart: always
    environment:
    - SOCAT_LINK=false
    - RUN_CROND=true
    ports:
    - "10080:10080"
    - "10022:22"
    volumes:
    - ../../data/git/gogs:/data
